### ISSUE TITLE
assign specific icon from file or exec

### ISSUE THREAD

**Issue by geosone** [DanysysTeam/SFTA#1]
it would be great to assign a specific icon from an dll or exe as an otion to the tool

this way the cracy reg add ..... marathon could be removed (7zip.dll icon matrix)

**Comment by Danyfirex** [comment]
You're right. We will add it for the next update.

**Comment by geosone** [comment]
thx for this great news then this can die. 
http://git.disconnected-by-peer.at/go-opsi/7zip.7zip/tree/CLIENT_DATA/setup3264.ins#n113
