### ISSUE TITLE
Error level on successful -r command

### ISSUE THREAD

**Issue by highend** [DanysysTeam/SFTA#3]
Hi,
```
SFTA.exe -r "D:\Tools\Media Player Classic HC - BE_x64\mpc-be64.exe" ".mkv"
```
It is successful (I've tested it by registering it with the same command and an appended -d before and unregistered it afterwards (again with -d to make sure there were no errors)

but
```
echo %errorlevel%
```
returns
```
-1073741819
```
instead of
```
0
```

**Comment by Danyfirex** [comment]
Hello, Could You do some other test maybe with notepad. I'm not able to reproduce the issue.

I've tested exactly as you show above from a cmd prompt and a .bat file and it returns 0 correctly.
