### ISSUE TITLE
Error: The specifield buffer is 0

### ISSUE THREAD

**Issue by Diamond186** [DanysysTeam/SFTA#4]
![image](https://user-images.githubusercontent.com/16068589/89188828-d9e2de00-d5a7-11ea-8790-b055331c5717.png)

cmd as admin
SFTA.exe --reg "E:\ProgramFiles\x32\Notepad++\Notepad2.exe" ".txt"

But work on x86

**Comment by Danyfirex** [comment]
It's designed to work as a x86 tool only. It will work in both OS Arch (x86 & x64) compiled as x86.
