### ISSUE TITLE
compilation

### ISSUE THREAD

**Issue by qzmtch** [DanysysTeam/SFTA#6]
I have such a question about compilation, this error constantly flies, on version 5.24 [screenshot](https://i.imgur.com/za1Joef.png) 
but on the latest version 5.73, this is the error [screenshot](https://i.imgur.com/kpEWz7Z.png)
could you please release a compiled executable file?

**Comment by Danyfirex** [comment]
Hello @qzmtch You can get a compiled version from my blog.

https://danysys.com/set-file-type-association-default-application-command-line-windows-10-userchoice-hash-internal-method/

I'll provide a compiled version by here later too. I'll also check your issues while compiling later.

Regards

**Comment by qzmtch** [comment]
Thanks!
